window.addEventListener("DOMContentLoaded",function(){const filterArea=document.querySelector('.filter-area');region_filter=filterArea.appendChild(createFilter('region','Region',["Mumbai","KSA","UAE","London","Zurich","Singapore","Frankfurt","Bahrain","Cape Town","Virginia","Jakarta","Johannesburg","Sydney"],get_user_region()));const selected_region=region_filter.querySelector('select').value;set_flag(selected_region);toggle_currency(selected_region);toggle_region_specific_pricing(selected_region);region_filter.querySelector('select').addEventListener('change',function(){set_flag(this.value);toggle_currency(this.value);toggle_region_specific_pricing(this.value);sessionStorage.setItem('filter-region',this.value);});document.getElementById('plan-type-switch')?.addEventListener('change',function(e){let selected_region=get_selected_region();let toggleDivs=document.querySelectorAll(`.region-${selected_region.replace(' ', '')}.basic`);toggleDivs.forEach(function(div){div.style.display=e.target.checked?'none':'table-row';});toggleDivs=document.querySelectorAll(`.region-${selected_region.replace(' ', '')}.enterprise`);toggleDivs.forEach(function(div){div.style.display=e.target.checked?'table-row':'none';});});function createFilter(name,label,options,selected=null){const filter=document.createElement('div');filter.classList.add('filter');const keyName=`filter-${name}`;const value=sessionStorage.getItem(keyName)||selected;filter.innerHTML=`
			<select name="${name}" id="${name}" aria-label="Select ${label}">
				<option value="" disabled>${label}</option>
				${options.map(option => `<option value="${option}"${value==option?'selected':''}>${option}</option>`)}
			</select>
		`;return filter;}
function get_user_region(){const user_timezone=Intl.DateTimeFormat().resolvedOptions().timeZone;const timezone_map={"Asia/Kolkata":"Mumbai","Asia/Calcutta":"Mumbai","Asia/Riyadh":"KSA","Asia/Aden":"KSA","Asia/Dubai":"UAE","Asia/Muscat":"UAE","Europe/London":"London","GB":"London","Europe/Zurich":"Zurich","Europe/Berlin":"Zurich","Asia/Singapore":"Singapore","Asia/Brunei":"Singapore","Asia/Bahrain":"Bahrain","Asia/Qatar":"Bahrain","Africa/Johannesburg":"Johannesburg","Africa/Windhoek":"Cape Town","America/New_York":"Virginia","America/Detroit":"Virginia","Asia/Jakarta":"Jakarta","Asia/Pontianak":"Jakarta","Asia/Makassar":"Jakarta","Asia/Jayapura":"Jakarta"};return timezone_map[user_timezone]||"Virginia";}
function get_country_code_based_on_region(region){const region_map={"Mumbai":"in","KSA":"sa","UAE":"ae","London":"gb","Zurich":"ch","Singapore":"sg","Frankfurt":"de","Bahrain":"bh","Cape Town":"za","Virginia":"us","Jakarta":"id","Johannesburg":"za","Sydney":"au",};return region_map[region]||"us";}
function set_flag(region){const country_code=get_country_code_based_on_region(region);document.querySelector('.region-flag').src=`https://flagcdn.com/h60/${country_code}.webp`;}
function toggle_currency(region){let isINR=region==='Mumbai';try{isINR=get_user_region()==="Mumbai";}catch(_){}
document.querySelectorAll('.inr_price').forEach(function(el){el.style.display=isINR?'inline':'none';});document.querySelectorAll('.usd_price').forEach(function(el){el.style.display=isINR?'none':'inline';});}
function toggle_region_specific_pricing(region){if(!document.getElementById('plan-type-switch'))return
const enterprise_plan=document.getElementById('plan-type-switch')?.checked;const class_name=`region-${region.replace(' ', '')}`;const plan_type_class=enterprise_plan?'enterprise':'basic';document.querySelectorAll('.plans.server-plans').forEach(function(el){el.style.display=(el.classList.contains(class_name)&&el.classList.contains(plan_type_class))?'table-row':'none';});}})
function get_selected_region(){return document.querySelector('.filter-area select[name="region"]').value;}